# global settings
title: "Elementary Inquiry"
description: "How does a project-based STEM learning environment increase authentic student engagement in Elementary Math, Science and the new Design and Coding curriculum?"
theme: jekyll-theme-minimal
